version: '3.8'

services:
  webapi_1: &api
    image: bruno-rinha
    hostname: webapi_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5292:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=rinhadb;User Id=myuser;Password=mypassword;
  webapi_2:
    <<: *api
    hostname: webapi_2
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=rinhadb;User Id=myuser;Password=mypassword;
    ports:
      - "5293:8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - webapi_1
      - webapi_2
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.17"
    #       memory: "10MB"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "6543:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./config/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  postgres_data:
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1