version: '3.8'

services:
  webapi:
    image: bruno-rinha
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5292:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=rinhadb;User Id=myuser;Password=mypassword;
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
networks:
  app-network: