version: "3.5"

services:
  application1: &application1
    image: wladimirteixeiraneto/rinha-mongo:latest
    network_mode: host
    restart: on-failure 
    depends_on:
      - mongodb        
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "125MB"
    environment:
      - MONGO_URI=mongodb://user:pass@localhost/Rinha?authSource=admin
      - PORT=5001
    
  application2:
    <<: *application1
    environment:
      - MONGO_URI=mongodb://user:pass@localhost/Rinha?authSource=admin
      - PORT=5002

  nginx:
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - application1
      - application2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    
  mongodb:
    image: mongo
    hostname: mongodb
    network_mode: host
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"
